# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField(verbose_name='预约时间')),
                ('state', models.CharField(choices=[('1', '未预约'), ('2', '待确认约定'), ('3', '已约定'), ('4', '已取消可重新约定'), ('5', '已完成'), ('6', '已禁止')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64, verbose_name='约谈主题')),
                ('description', models.TextField(verbose_name='简述约谈内容')),
                ('email', models.CharField(max_length=64, verbose_name='电子邮箱')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('mobile_number', models.CharField(max_length=16, verbose_name='手机号码')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, verbose_name='电子邮箱')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('datetime', models.DateTimeField(default=datetime.datetime, verbose_name='注册时间')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.AppointmentInformation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='make', to='appointment.User'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='appointment.User'),
        ),
    ]
