# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.AppointmentInformation'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_maker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='make', to='appointment.User'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='appointment.User'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('1', '未预约'), ('2', '待确认约定'), ('3', '已约定'), ('4', '已取消可重新约定'), ('5', '已完成'), ('6', '已禁止')], default='1', max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='appointmentinformation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=64, verbose_name='电子邮箱'),
        ),
    ]
